<#
.SYNOPSIS
imports a CSV that has been generated by cPanel account lists. and removes spaces from headers so fields can be read by powershell

.DESCRIPTION
imports a CSV that has been generated by cPanel account lists. and removes spaces from headers so fields can be read by powershell


.PARAMETER inputFile
the path of the filename to import

.EXAMPLE
 Import-CSVFromCPanel -inputFile .\kisshost.csv 

.NOTES
General notes
#>
function Import-CSVFromCPanel {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [string]
        $inputFile
    )
    $rawInput = import-csv $inputFile 
    Write-Verbose "About to Process $($rawInput.count) cPanel Account entries and remove spaces from headers"
    foreach ($i in $rawInput) {
        $result = [pscustomobject]@{
            Domain           = $i.Domain
            IP               = $i.IP
            Package          = $i.Package
            BytesUsed        = $i."Disk Space Used (bytes)"
            BytesQuota       = $i."Quota (bytes)"
            IsSuspended      = $i."Is Suspended"
            SuspecsionReason = $i."Suspension Reason"
            Comment          = $i."Upgrade Opportunities"
        }
        $result
    }
    write-verbose "Finished importing the cPanel CSV and remomving spaces from headers"
}
